print("-"*18)
print("Reajuste Salárial")
print("-"*18)
nome = str(input("Digite o nome do(a) colaborador(a): "))
salario = float(input("Qual o salário do(a) colaborador(a) ? "))
nvsalario = salario+(salario*0.15)
print("-"*18)
print("Nome: {}\nSalário: R$ {}\nNovo salário: R$ {:.2f}".format(nome, salario, nvsalario))
print("-"*18)
