print("-"*17)
print("Aluguel de Carros")
print("-"*17)
dias = int(input("Por quantos dias o carro foi alugado ? "))
kms = float(input("Quantos Kms foram rodados ? "))
print("-"*17)
totalapagar = (dias*60)+(kms*0.15)
print("Valor por dia: R$ 60\nValor por Kms rodados: R$0.15")
print("Dias alugados: {}\nKms rodados: {}\nValor total a pagar: R$ {:.2f}".format(dias, kms, totalapagar))
