print("-"*23)
print("Calculador de Descontos")
print("-"*23)
valor=float(input("Digite o valor do produto: R$ "))
vlrdesc=int(input("Digite a porcentagem do desconto: "))
vlrfinal=valor-(valor*(vlrdesc/100))
print("-"*23)
print("O valor final do produto com {}% de desconto é de: {:.2f}".format(vlrdesc,vlrfinal))
print("-"*23)